### PR TITLE
fix(generateMetricImage): export splitted graphs

### LINKED ISSUE #7312: [GRAPHS] Can't export 'splitted' graphs
<h1>BUG REPORT INFORMATION </h1>

<h3> Prerequisites </h3>

***Versions***
```
[root@localhost ~]# rpm -qa | grep centreon-web
centreon-web-18.10.3-5.el7.centos.noarch
```
***Operating System***

```
[root@localhost ~]# cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core) 
```

<h3> Description </h3>

It is not possible to export 'splitted' graphs.

<h3> Steps to Reproduce </h3>

1. Go to Monitoring -> Performances -> Graphs
2. Select a service that has several metrics
3. Display those by splitting the main graph
4. Try to export

<h3> Describe the received result </h3>

**ERROR 500**

<h3> Describe the expected result </h3>

Graph exported.

### PR DESCRIPTION
**Pull request by adr-mo**
<h1> Pull Request Template </h1>

<h2> Description </h2>

Remove unused code
Fix the graph export for splitted charts

Fixes #7312 

<h2> Type of change </h2>

Please delete options that are not relevant.

- [x] Patch fixing an issue (non-breaking change)

<h2> Target serie </h2>

Please delete series that are not relevant.

- [ ] 18.10.x
- [ ] 19.04.x (master)

<h2> How this pull request can be tested ? </h2>

1. Go to Monitoring -> Performances -> Graphs
2. Select a service that has several metrics
3. Display those by splitting the main graph
4. Try to export

<h2> Checklist </h2>

<h5> Community contributors & Centreon team </h5>

- [x] I followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

<h5> Centreon team only </h5>

- [x] I have made sure that the **unit tests** related to the story are successful.
- [x] I have made sure that **unit tests covers 80%** of the code written for the story.
- [ ] I have made sure that **acceptance tests** related to the story are successful (**local and CI**)

### CODE REVIEW

**Comment by CPbN** [comment]
Let's merge this tiny PR ?
Many thx :+1:

**Comment by adr-mo** [comment]
Hi @CPbN 

I'll create what needs to be created so that we can merge this PR.

It has to be tested by the QA

Regards

**Comment by CPbN** [comment]
Note that this issue is also solved in #7676 : "_Fix export png for splitted graph_".
We could then close this one.

**Comment by adr-mo** [comment]
@CPbN I can close this one ?

**Comment by CPbN** [comment]
Yes sure, thank you @adr-mo.

**Pull request closed without merging**
