### PR TITLE
Rights "delete" for the share views

### PR DESCRIPTION
**Pull request by jben94**
Add rights "delete" for the share views

New pull request, replace #4797 and #4798.

### CODE REVIEW

**Comment by kduret** [comment]
I will test it soon ;)

**Comment by jben94** [comment]
I will recheck, but this code is produced here.

**Comment by kduret** [comment]
It does not seem to work 

Share from admin : 
image

View from my user : 
image

=> I can delete view, even if I checked "no" to "deleteable ?"

I think you can wait before new commits, I will talk about this feature with the Product Owner

**Comment by jben94** [comment]
I just looked and I did not find any error in the changes.

When you say "I can delete view", did you click the button and the view was deleted for everyone, even the creator? Or is there still the "Delete view" button?

If you apply the changes of the Pull request "", maybe you will understand better.

**Comment by jben94** [comment]
The "Delete view" button is there either to delete the view or to hide it (Locked: NO or YES).

**Comment by lpinsivy** [comment]
Hi @jben94,

For Centreon Web 2.8.5 we rewrited users et groups permissions to have :

- Locked users
- Non locked users
- Locked groups
- Non locked groups

Locked users/groups have only the permission to add or delete an existing shared view.
Non locked users/groups can add or delete an existing shared view and modify this view.

I’m not sure it is necessary to add delete permission because all user must have permission to remove a view from their custom view dashboard. But the idea from #4801 to change text “delete” by “hide” for locked users/groups it a good idea.

Regards,

**Comment by jben94** [comment]
Hi @lpinsivy ,

I do not know the new rights because I am not yet at this version, but we made these changes because it allows the unlocked user to modify the views without being able to delete it (just hide it).

**Pull request closed without merging**
