### PR TITLE
Second version of relevant API tests for QA automation.

### PR DESCRIPTION
**Pull request by paul-oureib**
## Description

This commit contains the second draft of a Postman collection whose goal is to showcase and test different usual operations performed on centreon-platform, as a way of improving test automation. A detailed description of this collection is written here. Will be updated regularly.
A detailed description of this collection is written [here](https://centreon.atlassian.net/wiki/spaces/RD/pages/1962115093/Inventory+of+API+tests).
Will be updated regularly.

**Fixes** # (issue)

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [x] 23.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

### CODE REVIEW

**Review by sc979 — COMMENTED** [review]
Too many unmodified files are displayed.
Did you change the new line breaktype ? (CRLF vs LF vs CR)

**Comment by SoldierBoy31** [comment]
What's about this PR ? There are several rewrites of the same codes, what's the purpose ? We may can close it.

**Comment by Thebarda** [comment]
@paul-oureib Can you answer to the Loïc's question please?

**Comment by paul-oureib** [comment]
It seems I indeed had a problem with line breaktypes on my IDE, sorry for the inconvenience. Will close the PR now.

**Pull request closed without merging**
