### PR TITLE
enh(web): centreon compatibility with http2

### PR DESCRIPTION
**Pull request by sc979**
## Description

Remove he xsltRequest.statusText check as in http2 an empty string is returned.

**Fixes** # (#6337)

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [x] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 2.8.x
- [ ] 18.10.x
- [ ] 19.04.x
- [x] 19.10.x
- [x] 20.04.x (master)

<h2> How this pull request can be tested ? </h2>

Check no regression was added on each supported browser

#### Community contributors & Centreon team

- [x] I followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

#### Centreon team only

- [ ] I have made sure that the **unit tests** related to the story are successful.
- [ ] I have made sure that **unit tests cover 80%** of the code written for the story.
- [ ] I have made sure that **acceptance tests** related to the story are successful (**local and CI**)

### CODE REVIEW

**Comment by sc979** [comment]
The modification is in this commit : https://github.com/centreon/centreon/pull/8424/commits/63709743d6483af150bd86d4378556327f8d9b44
the " && xsltRequest.statusText == "OK" " part removal

**Comment by sc979** [comment]
Please do not merge this PR until further testing are achieved !!!

**Comment by lpinsivy** [comment]
@sc979 which can of tests do you mean?

**Comment by cgagnaire** [comment]
Doc ref https://docs.centreon.com/current/en/administration/secure-platform.html#enabling-http2

**Pull request merged**
