### PR TITLE
6530 standardize mail notifications

### PR DESCRIPTION
**Pull request by adr-mo**
Simple replica of #6530 .

Work has been rebased on the latest **2.8.x**
New branch created for CI matters (validation and automatic tests modified)

Code validation has been already done.

### CODE REVIEW

**Comment by adr-mo** [comment]
Looks good to me can now be merged on the **2.8.x**

**Comment by CPbN** [comment]
Thank you @adr-mo :+1: 
I wondered whether or not `<str>` would have to be changed to `&lt;str&gt;`, but sounds then like no.
But re-reading the changes, I would say some `&quot;` have useless `$` sign in front of them.
For example :
`-r $&quot;Centreon <centreon-engine>$&quot; -S replyto=$&quot;Centreon admin <$ADMINEMAIL$>$&quot;`
Finally would require some update I think.

**Comment by CPbN** [comment]
I've corrected in the initial PR #6530.

**Comment by adr-mo** [comment]
If it worth changing the code do not hesitate to do so 😊 I'll do the validation one more time there is no issue with that 😉

**Comment by CPbN** [comment]
Thank you :+1: 
I've submitted 2 additional _Typo_ commits to the PR, you can go !

**Comment by adr-mo** [comment]
Ok perfect I will cherry-pick them to this branch and validate the PR.

Thanks again for the contribution 😉

**Comment by CPbN** [comment]
In addition, do you know why `"` are replaces by the HTML entity `&quot;` ?
The notification commands are the only ones to use this "trick".
All other ones use `"`.
In addition, if you add a command through Crenteon GUI and then look at the inserted MySQL line, you'll see `"`, not `&quot;`.
Do you think we could get rid of them ?

**Comment by adr-mo** [comment]
@CPbN I don't know, maybe @lpinsivy or @leoncx could answer to your question :)

**Comment by CPbN** [comment]
Thank you @adr-mo, let's then wait for their answer before merging :+1:

**Comment by CPbN** [comment]
Thank you @leoncx :+1: 
So we can now safely replace these HTML entities by their corresponding characters, right ?

**Comment by CPbN** [comment]
We can also go like this, the `"` vs `&quot;` is not really important, rather cosmetic :)

**Pull request merged**
