### PR TITLE
feat(ui): Hide / show graph line in Event details view

### PR DESCRIPTION
**Pull request by bdauria**
## Description

This adds the possibility of hiding / showing lines on the performance graph (only on the details panel):

toggable-legend

## Type of change

- [x] New functionality (non-breaking change)

## Target serie

- [x] 20.04.x (master)

### CODE REVIEW

**Comment by Moujimouja** [comment]
yep, no doubt that a checkbox is not what users want. Name should be clickable (as 100% graph libs do)

**Comment by bdauria** [comment]
@kduret @Moujimouja the new behaviour with latest changes is as follow:

hideshow

**Comment by kduret** [comment]
Since there is no more checkbox, I think the colored circle can be retrieved to the left of the metric label

**Comment by Moujimouja** [comment]
> Since there is no more checkbox, I think the colored circle can be retrieved to the left of the metric label

agreed, do not change the circle position

**Comment by bdauria** [comment]
@Moujimouja @kduret Legend icon moved back to the left hand side:

Screenshot from 2020-05-13 19-58-05

**Comment by Thebarda** [comment]
LGTM with latest changes 👍 

graph1

graph2

**Pull request merged**
