### PR TITLE
The extra legend is option in chart.

### PR DESCRIPTION
**Pull request by leoncx**

### CODE REVIEW

**Comment by thiuyendang** [comment]
Centreon Web 2.8.5, CentOS7, Graph monitoring  widget 1.5.1

**Comment by thiuyendang** [comment]
Checked with Centreon Web 2.8.7, Widget Graph Monitoring 1.5.1.
The "i" and toggle option buttons are still enabled, only pictures are not visible anymore.

**Comment by cgagnaire** [comment]
Is this related to https://github.com/centreon/centreon/pull/5159 ?
Anyway, widget does not work for me in 2.8.9-2 with 'Graph Monitoring' widget in 1.5.1-1.
Got the error : 
PHP Notice:  Undefined variable: servicePreferences in /usr/share/centreon/www/widgets/graph-monitoring/index.php on line 122, referer: http://10.30.2.131/centreon/widgets/graph-monitoring/index.php?widgetId=4&customViewId=1

**Comment by thiuyendang** [comment]
Tests in 2.8.9-5 : buttons are hidden and not visible (in page Home > Custom views)

**Pull request merged**
