### PR TITLE
fix(topology) Correct URL options for service pages

### LINKED ISSUE #6162: Services Grid, Services by (host|service)groups display "All" instead of "Problems" as the filter suggests
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: centreon-web-2.8.19-4.el7.centos.noarch

**Centreon Engine version**: centreon-engine-1.8.1-1.el7.centos.x86_64

**Centreon Broker version**: centreon-broker-core-3.0.13-1.el7.centos.x86_64

**OS**: centos-release-7-4.1708.el7.centos.x86_64

**Additional environment details (AWS, VirtualBox, physical, etc.):** several types of hardware or virtual environments
**Steps to reproduce the issue:**
1. Go to Monitoring / Status Detail / Services grid
2. Or go to Monitoring / Status Detail / Services by Hostgroups
3. Or go to Monitoring / Status Detail / Services by Servicegroups

**Describe the results you received:**
"Display details" filter (which, by the way, is not well named, maybe "Status filter" would be better ) is set to "Problems" BUT actually displays "All". You have to apply another filter and then get back to "Problems" to actually display problems only.

**Describe the results you expected:**
Displaying problems only, as the filter suggests.

**Additional information you think important (e.g. issue happens only occasionally):** none

### PR DESCRIPTION
**Pull request by CPbN**
Hi,

<h2> Description </h2>

This PR closes #6162, where the default  "Display details" filter set to Problems is not enforced in Moniotring Services views.

<h2> Type of change </h2>

- [x] Patch fixing an issue (non-breaking change)

<h2> Target serie </h2>

Please delete series that are not relevant.

- [x] 20.04.x (master)

<h2> How this pull request can be tested ? </h2>

Go to Monitoring / Status Detail / Services grid
Go to Monitoring / Status Detail / Services by Hostgroups
Go to Monitoring / Status Detail / Services by Servicegroups

And verify that the default "Display details" filter set to Problems is correctly active.

Edit : issue still present in 19.10.3.

### CODE REVIEW

**Comment by adr-mo** [comment]
Hi @CPbN,

Thanks for the contribution :100: 

We'll try to make your work happen in Centreon as soon as possible :+1: 

Regards,

**Comment by CPbN** [comment]
Conflicts solved.
Perhaps we could merge this before 18.10.5 is released, to avoid having to rebase this PR again ?
Thank you :+1:

**Comment by CPbN** [comment]
Rebased for 19.04.1.
Could we then think about adding this to the [19.04.1 project](https://github.com/centreon/centreon/projects/39) please ?
Thank you :+1:

**Comment by CPbN** [comment]
Rebased for 19.04.1.
@lpinsivy Laurent could we then think about adding this tiny PR to the [19.04.1 project](https://github.com/centreon/centreon/projects/39) please, so that I don't have to change SQL filename on every release ? :)
Many thanks :+1:

**Comment by adr-mo** [comment]
Hi @CPbN 

I'll request some reviews for this PR so that we can start the validation on it :)

@lpinsivy I am adding this to the **19.04.1**

Regards,

**Comment by CPbN** [comment]
Hi @adr-mo, and thank you very much !

**Comment by CPbN** [comment]
@adr-mo, sounds like this has been moved to DONE status without having been implemented ? :-|
Thank you !

**Comment by CPbN** [comment]
Rebased for 19.04.3.
Let's try to merge it ? :)
Thx again :+1:

**Comment by CPbN** [comment]
For info this fix was already pushed in Centreon 2.7.1 : [Update-DB-2.7.1.sql](https://github.com/centreon/centreon/blob/master/www/install/sql/centreon/Update-DB-2.7.1.sql).
Unfortunately, insertTopology.sql was not updated at the same time.
This is what this PR does.

**Comment by CPbN** [comment]
Rebased for 19.10.0.

**Comment by sc979** [comment]
@adr-mo , forking, rebasing and launching a job on the CI for you to be able to test TNR ;)
check branch : 
`CPbN-fix-topology-url-for-service-pages`

**Comment by sc979** [comment]
I resolved conflict and updated the SQL upgrade script to 18.10.x and 19.04 branches

**Comment by CPbN** [comment]
Let's put this into 19.10 please ?
Many thanks 👍

**Comment by CPbN** [comment]
Issue still in 19.10.0-beta.2, let's then merge this fix please ?
Thank you !

**Comment by CPbN** [comment]
I think we should definitely merge this, if you have a chance to look at it :)
Thank you again !

**Comment by CPbN** [comment]
Issue still in 19.10.0-rc.1, let's then merge this fix please ?
Thank you !

**Comment by CPbN** [comment]
Rebased for 19.10.2.

**Comment by CPbN** [comment]
Just rebased again.
@kduret could you please re-approve this so that we can move on ?
Thank you !

**Comment by adr-mo** [comment]
Hi @CPbN 
I'll create a branch from Centreon repository with your work for building / validation matters.
In fact the build of your work fails on our acceptance tests but it is not related to your work ;)

This will avoid to ask you to rebase your work everytime some changes are pushed on master.

I'll let you know when the validation is done, and your work merged :)

Thanks again for the contribution :100:

**Comment by adr-mo** [comment]
Branch created `MON-4140-topology-services-issue` and currently being built :)

**Comment by adr-mo** [comment]
@CPbN PR created above yours so that we can easily validate it :)

**Comment by CPbN** [comment]
Good news, many thanks @adr-mo 👍
Glad to see it almost landed 😉

**Pull request closed without merging**
