### PR TITLE
Fix regression from #1841

### PR DESCRIPTION
**Pull request by sathieu**
sso_username does not always contain an "@"

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Thanks for the feedback. i have seen it this morning. I'm working on a patch.

**Comment by sathieu** [comment]
@garnier-quentin My patch doesn't fit?

**Comment by garnier-quentin** [comment]
It works but i prefer to add options to do some regexp change. It will be more flexible.

**Comment by garnier-quentin** [comment]
Ref 432ff2b30c86827dd9f29bda54cb753bc219046c

**Pull request closed without merging**
