### PR TITLE
fix(doc): correct link references in IMP chapter

### PR DESCRIPTION
**Pull request by lpinsivy**

### CODE REVIEW

**Comment by thiuyendang** [comment]
Cannot click on the links and link is not displayed as expected

**Comment by thiuyendang** [comment]
Still not OK

**Comment by thiuyendang** [comment]
Please, remove the "_" sign at the end of your ref link. AMO has tested without and the link is displayed properly and can be clicked.

**Comment by lpinsivy** [comment]
done!

**Pull request merged**
