### PR TITLE
Doc correct build errors

### PR DESCRIPTION
**Pull request by lpinsivy**
Numerous corrections to correct errors when generating documentation.

### CODE REVIEW

**Comment by lgcosta** [comment]
@lpinsivy Will this not that break together with this request https://github.com/centreon/centreon/pull/6510 ?

**Comment by lpinsivy** [comment]
@lgcosta if you change some title level inconsistent or you add missing release note of Centreon Web 2.7.11 yes a merge will be needed.

I will check your PR

**Comment by lgcosta** [comment]
Thanks @lpinsivy. Yes, i have changed some titles, especially in the API pages. But the release note i do not really have here. We can join these PR, what do you think?

**Comment by chgautier** [comment]
Changes verified on branch doc-correct-build-errors. Alright for merge.

**Pull request merged**
