### PR TITLE
enh(ui): Add nowrap style to badge class to avoid wrap in dense typeface environments like chinese.

### PR DESCRIPTION
**Pull request by aladdinchan**
## Description
Before add nowrap style: 
The status column text (chinese word) wrapped undesired.
image

After:
The status column text unwrapped.
image

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 2.8.x
- [ ] 18.10.x
- [ ] 19.04.x
- [x] 19.10.x
- [x] 20.04.x (master)

#### Community contributors & Centreon team

- [x] I followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

#### Centreon team only

- [ ] I have made sure that the **unit tests** related to the story are successful.
- [ ] I have made sure that **unit tests cover 80%** of the code written for the story.
- [ ] I have made sure that **acceptance tests** related to the story are successful (**local and CI**)

### CODE REVIEW

**Comment by lpinsivy** [comment]
Hi @aladdinchan why do you close you PR?

**Comment by aladdinchan** [comment]
Sorry, I don't known why.  I just change the branch name.  then PR closed automatically.

**Comment by lpinsivy** [comment]
Added in our backlog for next sprint

**Comment by kduret** [comment]
Hi @aladdinchan ,

Could you attach your translation file please ? (.po extension)

Thanks !

**Comment by aladdinchan** [comment]
The translation is in progress.  I’ll be glad to commit when completed.

**Comment by sc979** [comment]
Hi @aladdinchan ,
I reproduced your issue using the translation made by @zheddiewen.
https://github.com/zheddiewen/centreon-translation/tree/master/zh_CN/LC_MESSAGES
We couldn't merge his work 2 years ago, cause the help.po file was missing.

**Comment by sc979** [comment]
@aladdinchan,
Adding the "nowrap"  argument to the ListColNoWrap impact more than only badges (every listing pages and many widgets) and isn't required to fix the badges.
I opened another PR here https://github.com/centreon/centreon/pull/8314, with only your first commit.
That's why I'm closing this one.
Best Regards,
sc979

**Comment by sc979** [comment]
The PR #8314 is merged with your commit and will be available in the release 19.10.7.
Thanks @aladdinchan

**Pull request closed without merging**
