### PR TITLE
enh(sec): log failed login attempts (ban post processing)

### PR DESCRIPTION
**Pull request by CPbN**
Hi,

<h2> Description </h2>

This PR simply logs failed login attempts.
Goal is then for the system administrator to be able to use tools such as fail2ban to ban IPs generating too many failed login attempts.
As fail2ban generally already analyzes Apache error log file, these error messages are directly sent to it (thanks to the second option of `error_log` set to `4`).

<h2> Type of change </h2>

- [x] New functionality (non-breaking change)

<h2> Target serie </h2>

- [x] 19.04.x
- [x] 19.10.x (master)

<h2> How this pull request can be tested ? </h2>

`tail -f /var/log/httpd24/error_log`
Make failed login attempts (easy) !

Thank you :+1: 

Edit : still missing from 19.10.0-beta.2.

### CODE REVIEW

**Comment by CPbN** [comment]
Many thanks @sc979 :+1:

**Comment by kduret** [comment]
It seems that fail2ban is able to read other files.
So it should be more relevant to read this file : /var/log/centreon/login.log
Instead of adding another line in apache logs

**Comment by CPbN** [comment]
Goal is also to avoid increasing number of files to read from Fail2Ban, to avoid load impact.
As Fail2Ban already reads the Apache error log file (of course if admin enables the Apache jail), then the error messages from this PR will be caught without having to process another file.
I could tune message a little bit to tell that they come from Centreon :)

**Comment by CPbN** [comment]
Would be nice to have this in 19.10 ?
Thank you !

**Comment by kduret** [comment]
@lpinsivy I guess you can confirm, but we will not add applicative logs in apache logs.
sorry for that @CPbN

**Comment by CPbN** [comment]
@kduret that's a pity :confused:
I think Apache error log (the one targeted by this PR) is the good place to log such error messages :

- if you install Fail2Ban, you will for sure enable the Apache jail for common Apache rules, you will then already check Apache error log file : we then minimize load impact and simplify config ;
- Apache already sends _authentication failed_ error messages into its error log file, for example when HTTP basic authentication is used : makes then sense for HTTP applications (such as Centreon) to send their _authentication failed_ error messages to this error log file.

In addition, and for security reasons, this PR is a good thing to have, to protect against unauthorised access attempts. Think about Centreon servers reachable through Internet / public networks for example...

May I then ask you to reconsider this PR, as per the previous various arguments ?

Thank you again for your support 👍

**Comment by CPbN** [comment]
@kduret @lpinsivy did you manage to double-check this ?
Thank you very much again 👍

**Comment by kduret** [comment]
HTTP basic authentication is directly related to HTTP, so it makes sense to put it in apache logs.
But Centreon authentication is related to Centreon web,  and should not be part of apache logs (even if configuration of fail2ban is more complex)

So, sorry for that, but we will definetely not merge this PR.

**Comment by CPbN** [comment]
Thank you @kduret for your additional feedback.
What would then be the correct destination for such messages ?
An existing log file ?
A new one (`/var/log/centreon/login.log` as you seemed to propose above) ?

I can submit a new PR with your desired target.
Thank you !

**Comment by CPbN** [comment]
Thank you @kduret for your additional feedback.
Then see #7943 for another solution which should suit you :+1:

**Pull request closed without merging**
