### PR TITLE
fix(backup): remove warning messages

### PR DESCRIPTION
**Pull request by lpinsivy**
## Description

Remove warning:

```
[2020-09-24 13:06:31] Start central backup processus
[2020-09-24 13:06:49] Finish central backup processus
[2020-09-24 13:06:49] Start monitoring engine backup processus
Use of uninitialized value $from in string eq at /usr/share/perl5/File/Copy.pm line 102.
Use of uninitialized value $from in stat at /usr/share/perl5/File/Copy.pm line 138.
Use of uninitialized value $from in open at /usr/share/perl5/File/Copy.pm line 215.
No ssh keys for Centreon Engine
[2020-09-24 13:06:54] Finish monitoring engine backup processus
[2020-09-24 13:06:54] Start database backup processus
[2020-09-24 13:06:54] Finish database backup processus
```

**Fixes** #8621 and replace #8622

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 19.04.x
- [x] 19.10.x
- [x] 20.04.x
- [x] 20.10.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

- [ ] I followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

### CODE REVIEW

**Review by sc979 — APPROVED** [review]

**Review by kduret — APPROVED** [review]

**Comment by UrBnW** [comment]
@lpinsivy this was already addressed in #8734.

**Comment by lpinsivy** [comment]
Hi @UrBnW, for customer support I will merge this one and I will study soon your PR.

**Comment by UrBnW** [comment]
Seems like you forgot to backport this into `19.10.x` branch @lpinsivy 😉
Thank you 👍

**Comment by UrBnW** [comment]
@lpinsivy @sc979 seems like this was not backported into `19.10.x` branch.
It has certainly been missed, as it's in `19.04.x`.
Just not to forget it :)
Thank you 👍

**Comment by sc979** [comment]
@lpinsivy , indeed the commit has been backported to the 19.04 and it's missing on the 19.10

Thanks @UrBnW, I'll backport the fix on the 19.10 ASAP

**Pull request merged**
