### PR TITLE
remove old and unused file in order to avoid problems with ACL

### PR DESCRIPTION
**Pull request by julienmathis**

### CODE REVIEW

**Comment by adr-mo** [comment]
Ok I'm on it

**Comment by lpinsivy** [comment]
The best way is to make before a PR to add 2.8.26 and then base this PR on 2.8.x after merge previous one

**Comment by adr-mo** [comment]
OK I'll change that right away

**Comment by lpinsivy** [comment]
you need now to rebase and merge conflit ;)

**Comment by adr-mo** [comment]
Removed update script, to get the one from the 2.8.x and add the code from julien to it. Conflict resolved ;)

**Comment by adr-mo** [comment]
Looks good to me, can now be merged on the **2.8.x**

**Pull request merged**
