### PR TITLE
+ allow downtime scheduling from poller diplay

### PR DESCRIPTION
**Pull request by Sims24**
- https://github.com/centreon/centreon/issues/4241
- Replace query in getPollerID to allow dowtime scheduling from poller diplay (Use real time instances table)

### CODE REVIEW

**Comment by Sims24** [comment]
Any news on this @julienmathis  ? :) 

Maybe not the most efficient PHP code you've ever seen, but need of this feature remains :) Feel free to refactor if needded

Thanks

**Comment by garnier-quentin** [comment]
Cannot be merged. The table instances from centstorage is filled/updated when the poller (centreon-broker) has been started and communication works. But if not, we can not do some external commands. Need another way i think.

**Comment by lpinsivy** [comment]
@Sims24 the best way is to keep actuel code and catch centreon_poller_display module installed to change SQL request.

**Comment by Sims24** [comment]
Thanks @lpinsivy, I gonna make it as described.

**Comment by kduret** [comment]
#4241 is closed
Then I closed this pull request :)

**Pull request closed without merging**
