### PR TITLE
fix(ci): fix delivery using self hosted runners

### PR DESCRIPTION
**Pull request by kduret**
## Description

fix delivery using self hosted runners

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [x] 23.04.x (master)

### CODE REVIEW

**Comment by bdauria** [comment]
We should consider skipping deliver jobs altogether whenever the branch is not relevant for that (develop, dev-*...)

**Comment by kduret** [comment]
> We should consider skipping deliver jobs altogether whenever the branch is not relevant for that (develop, dev-*...)

develop branches must deliver in unstable.
Otherwise, QA team will not be able to validate using RPMs

**Comment by bdauria** [comment]
> > We should consider skipping deliver jobs altogether whenever the branch is not relevant for that (develop, dev-*...)
> 
> develop branches must deliver in unstable. Otherwise, QA team will not be able to validate using RPMs

Yes sorry I meant branches that aren't matching relevant ones for delivery

**Comment by kduret** [comment]
> > > We should consider skipping deliver jobs altogether whenever the branch is not relevant for that (develop, dev-*...)
> > 
> > 
> > develop branches must deliver in unstable. Otherwise, QA team will not be able to validate using RPMs
> 
> Yes sorry I meant branches that aren't matching relevant ones for delivery

But I don't know what the `if` should be, cause it does not accept regular expression

It could be something like this but it's too verbose and do not handle every cases : `if: ${{ startsWith(github.ref, 'refs/heads/dev') || startsWith(github.ref, 'refs/heads/hotfix-') || startsWith(github.ref, 'refs/heads/release-') || endsWith(github.ref, '.x') || startsWith(github.ref, 'refs/tags') }}`

Otherwise, the `get-version` job could output a `branch_type` which could be use in this expression. But can be managed in an other PR

**Review by sc979 — APPROVED** [review]

**Pull request merged**
