### PR TITLE
To fix issue #8306 Can't delete comment

### PR DESCRIPTION
**Pull request by rk4an**
# Pull Request Template

## Description

We can't delete comment in Monitoring, Downtimes, Comments

**Fixes** # #8306

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 2.8.x
- [ ] 18.10.x
- [x] 19.04.x
- [x] 19.10.x
- [x] 20.04.x (master)

<h2> How this pull request can be tested ? </h2>

Go to downtime > comment  and  delete a comment

#### Community contributors & Centreon team

- [x] I followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

#### Centreon team only

- [ ] I have made sure that the **unit tests** related to the story are successful.
- [ ] I have made sure that **unit tests cover 80%** of the code written for the story.
- [ ] I have made sure that **acceptance tests** related to the story are successful (**local and CI**)

### CODE REVIEW

**Comment by adr-mo** [comment]
Hi @rk4an 

Thanks for the contribution :100: 

Could you please fill the PULL_REQUEST_TEMPLATE please. This will help

- The reviewers that will validate your code
- The QA that will validate your work for a future release integration.

Thanks :+1:

**Comment by rk4an** [comment]
Done,

For Centreon 19.04.x and 19.10x

**Comment by cgagnaire** [comment]
Hi @rk4an,

Your work has been selected by the Team and moved to a new internal branch so that we can integrate it to our workflow.

Regards.

**Comment by cgagnaire** [comment]
Refs: MON-4855

**Comment by sc979** [comment]
Hi @rk4an,
I worked on your PR and found that it won't fix the issue impacting comments on hosts too (www/include/monitoring/comments/commentHost.php).
Another PR was merged and is available here : https://github.com/centreon/centreon/pull/8367
Thanks for your contribution.
Best Regards,
sc979

**Comment by sc979** [comment]
These modifications will be released in coming 18.10.13 / 19.04.12 / 19.10.9

**Pull request closed without merging**
