### PR TITLE
fix(UI): The size of login paper is different

### PR DESCRIPTION
**Pull request by Med1233**
## Description

The size of the login page is different comparing it with old version 

https://user-images.githubusercontent.com/109956462/208147322-15155303-3796-43e5-bb68-b8277612381c.mp4

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [x] 23.04.x (master)

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

### CODE REVIEW

**Review by Thebarda — APPROVED** [review]
It would be good to cover it with Cypress

**Comment by bdauria** [comment]
@Med1233 are you going to add the snapshot test in this PR?

**Comment by Med1233** [comment]
> @Med1233 are you going to add the snapshot test in this PR?

we will add cypress testing for the login page as part of the test migration task as suggested by Tom.

**Review by bdauria — APPROVED** [review]

**Comment by bdauria** [comment]
@Med1233 Ok, approved then

**Pull request merged**
