### PR TITLE
feat(event-view): Add shortcuts tab

### PR DESCRIPTION
**Pull request by bdauria**
## Description

This adds a tab with the shortcut links:

Screenshot from 2020-08-26 11-05-00

## Type of change

- [x] New functionality (non-breaking change)

## Target serie

- [x] 20.04.x
- [x] 20.10.x (master)

### CODE REVIEW

**Review by kduret — APPROVED** [review]

**Comment by Thebarda** [comment]
I think it is a bit confusing to display twice "Configure", "View logs" and "View report". The first time, I didn't see that the first is for the service. I think it would be better to display "Related Host" instead of "Host" and add a title like "Service" above the first card

**Comment by Moujimouja** [comment]
Agreed, as in the design, let's display the type above the first shortcut group

**Comment by kduret** [comment]
@Thebarda I have update shortcut section : 
image

I let you also check this commit : https://github.com/centreon/centreon/pull/8942/commits/e720bcb8129ae67bf25f243e03d270e72a228eec

**Comment by Thebarda** [comment]
Tested and LGTM with latest changes
shortcut-1
shortcut-2

**Review by Thebarda — APPROVED** [review]

**Review by kduret — APPROVED** [review]

**Comment by kduret** [comment]
@bdauria I let you check this commit : https://github.com/centreon/centreon/commit/e720bcb8129ae67bf25f243e03d270e72a228eec
If it's ok for you, you can merge

**Review by Thebarda — APPROVED** [review]

**Pull request merged**
