### PR TITLE
Update centreonAuth.class.php

### PR DESCRIPTION
**Pull request by Rico29**
related to #5186, second try

### CODE REVIEW

**Comment by Rico29** [comment]
What is the problem ?

**Comment by lpinsivy** [comment]
Yesterday I created a similar patch
[log_fail_connection.txt](https://github.com/centreon/centreon/files/989676/log_fail_connection.txt)

**Comment by lpinsivy** [comment]
Linked to #4989

**Comment by lpinsivy** [comment]
Hi,

I propose two format:

[2004-02-12T15:19:21+00:00][STATUS][IP][USER] - Message  (ISO 8601 format)
or
[Thu, 21 Dec 2000 16:01:07 +0200][STATUS][IP][USER] - Message  (RFC 2822 format)

Regards,

**Comment by kduret** [comment]
Your code does not respect PSR-2 (Lines exceed 120 characters).

I close this PR cause there is not answer since 3 months

**Pull request closed without merging**
