### PR TITLE
Fix wording related to downtimes

### PR DESCRIPTION
**Pull request by sbraz**
Two very small changes to the downtime-related messages.

### CODE REVIEW

**Comment by sc979** [comment]
Hi sbraz,

Thanks for your PR.

Sincerely,

sc979

**Comment by sc979** [comment]
Hi sbraz,

Your PR was merged on the 18.10.x and master branches.

Regards,

sc979

**Comment by sbraz** [comment]
Thanks @sc979. I just noticed that another menu says "Recurrent downtimes". I hope it's OK that I used the word recurring instead of recurrent.

**Comment by sc979** [comment]
@sbraz ,
You mean in the breadcrumb ? or the left side menu ?
sc979

**Comment by sbraz** [comment]
@sc979 on  the left side menu, yes. And apparently also on the breadcrumb.

**Comment by sc979** [comment]
@sbraz,

Yes that's fine. It doesn't seems incoherent at all.

Sincerely,

sc979

**Pull request merged**
