### PR TITLE
Proposal break Ajax

### PR DESCRIPTION
**Pull request by jben94**
Proposal to break Ajax requests to the WEB server, when the user is not on the page.

Following to a large number of requests (HTTP) to the main server of Centreon.
Because a user could make a large number of accesses, in relation to the tabs (or windows) opened on the interface of Centreon.

### CODE REVIEW

**Comment by lpinsivy** [comment]
Hi @jben94, great !!!

But I my opinion it will be better to keep "notification popup" and also "sound popup" event if you are not on "Monitoring page" and to have this on all Centreon web pages.

What do you think ?

**Comment by garnier-quentin** [comment]
Notification popup is not important. It's only in the centreon tab. (so you need visibilty)

**Comment by jben94** [comment]
In my changes, I do not block sound alerts.

**Comment by Dacchi** [comment]
Thanks for the contribution

**Pull request merged**
