### PR TITLE
translation(chinese): add chinese translation

### PR DESCRIPTION
**Pull request by kduret**
thanks to @zheddiewen !

### CODE REVIEW

**Comment by kduret** [comment]
Maybe we need to replace /home/icanwen/project/centreon-translation/centreon-github/ by centreon-web/

**Comment by zheddiewen** [comment]
@kduret I change it according to your request.

**Comment by lpinsivy** [comment]
@zheddiewen I installed your chinese translation and interface works correctly.

Can you also translate contextual help for forms (help.po)?

Thank you for your work.

**Comment by zheddiewen** [comment]
- @lpinsivy get it ! I will translate it !

**Comment by lpinsivy** [comment]
@zheddiewen thank you very much for your contribution

**Comment by sbrizini** [comment]
hi @zheddiewen ,

We are currently integrating your translation into the project. Have you had the opportunity to translate the help.po file as well ? 
Would be great to include both at the same time.

Thx again for your contribution

**Pull request closed without merging**
