### PR TITLE
Multi select widget

### PR DESCRIPTION
**Pull request by jben94**
Hi,

Here are the changes made to set up multiple selects in the widget configuration
Issue : #5039

### CODE REVIEW

**Comment by jben94** [comment]
Pull request, Centreon-Widgets/centreon-widget-host-monitoring : #23

**Comment by lpinsivy** [comment]
Thank for this pull request, already corrected by comit 9dfe0f7f7e441b2f9ba1662d9c194bf5621f231e

**Comment by jben94** [comment]
Hi,

I do not understand your message because you put a link that does not correspond to my modifications!

**Comment by jben94** [comment]
Hi,

New Issue : #4423

**Pull request closed without merging**
