### PR TITLE
feat(ui): Reorder Events view custom filters

### PR DESCRIPTION
**Pull request by bdauria**
## Description

This allows the user to reorder the listed custom filters via drag and drop:

reorder

## Type of change

- [x] New functionality (non-breaking change)

## Target serie

- [x] 20.04.x
- [x] 20.10.x (master)

### CODE REVIEW

**Comment by Thebarda** [comment]
We should align drag and drop icon with Auto Discovery (mappers)

**Comment by kduret** [comment]
> We should align drag and drop icon with Auto Discovery (mappers)

And the style too.
Should we use a kind of "Paper" behind of each filter ? like it's done in autodiscovery mappers

**Comment by bdauria** [comment]
@kduret @Thebarda new style: 
localhost_4000_centreon_monitoring_events (7)

**Comment by jdelpierre** [comment]
> @kduret @Thebarda new style:
> localhost_4000_centreon_monitoring_events (7)

Nice :)

**Comment by jdelpierre** [comment]
But I find that there is still a lot of extra space between the elements (that's my opinion).

**Comment by Thebarda** [comment]
> @kduret @Thebarda new style: 
> localhost_4000_centreon_monitoring_events (7)
> 

Nice ! But the unfold icon is on right side of Paper on Mappers instead of left side here

**Comment by jdelpierre** [comment]
I had made the remark about actions on the right, of course there has to be consistency, to see if you leave it to the left or right everywhere.

**Comment by bdauria** [comment]
done 
Screenshot from 2020-07-22 10-44-57

**Comment by jdelpierre** [comment]
It's Ok for me 
image

**Pull request merged**
