### PR TITLE
Update documentation to support 19.04 version (httpd24 mainly)

### PR DESCRIPTION
**Pull request by lgcosta**
<h1> Pull Request Template </h1>

<h2> Description </h2>

Update documentation to support 19.04 version (httpd24 mainly)

<h2> Type of change </h2>

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [x] Updating documentation (missing information, typo...)

<h2> Target serie </h2>

- [ ] 2.8.x
- [ ] 18.10.x
- [x] 19.04.x (master)

<h2> How this pull request can be tested ? </h2>

Following the documentation update

<h2> Checklist </h2>

<h5> Community contributors & Centreon team </h5>

- [ ] I followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

<h5> Centreon team only </h5>

- [ ] I have made sure that the **unit tests** related to the story are successful.
- [ ] I have made sure that **unit tests covers 80%** of the code written for the story.
- [ ] I have made sure that **acceptance tests** related to the story are successful (**local and CI**)

### CODE REVIEW

**Comment by adr-mo** [comment]
@lgcosta @lpinsivy This should be done also for 19.04.x

**Comment by lgcosta** [comment]
> @lgcosta @lpinsivy This should be done also for 19.04.x

Yes, I agree.

**Comment by lgcosta** [comment]
Yes @adr-mo I will try to validate this

Thanks

**Comment by lgcosta** [comment]
Hello @adr-mo

In the tests I do using the sources directly (over docker), I have used the 7.2 version of php until then with no problems. However, as the code distributed in RPM uses as dependency 7.1 version, by default I will change to this version. So we avoid any problem because of version.

I will change the PR.

Thanks !

**Comment by lgcosta** [comment]
done @adr-mo 
Thanks again

**Pull request merged**
