### PR TITLE
Disable the edit mode when connecting to the WEB interface.

### PR DESCRIPTION
**Pull request by jben94**
The problem exists when at least one created view.

### CODE REVIEW

**Comment by loiclau** [comment]
Hi,
The actionBar is displayed only after the second click on the button
Can you fix it?
Regards

**Comment by jben94** [comment]
Hi,
I do update for Fix the display.
Is it good for you?

**Comment by loiclau** [comment]
No, my first click doesn't work

**Comment by jben94** [comment]
Hi,
What browser do you use?
On Firefox and Chrome it works.

**Comment by jben94** [comment]
I just checked on IE and it works too.

**Comment by loiclau** [comment]
Hi,
The problem occurs when the custom view doesn t have widgets
Regards

**Comment by jben94** [comment]
Hi,
I do send the Fix

**Comment by loiclau** [comment]
Hi,
Thank you for your contribution.
Regards

**Pull request merged**
