### PR TITLE
Incrementing problem

### PR DESCRIPTION
**Pull request by jben94**
The 'cb_list_id' field is not auto-incrementing

### CODE REVIEW

**Comment by lpinsivy** [comment]
@ganoze can you give me your opinion on this PR please?

**Comment by cgagnaire** [comment]
Hi @jben94,
Sorry for the delay :D 
We are trying to catch up with old PR opened by community.
We are wondering what is the error, or how did you find the problem here ?
Can you help us, if you remember of course :)

**Comment by jben94** [comment]
Hi @cgagnaire,

Yes a long time ago! ;)
The problem is that the table 'cb_list' does not have autoincrement so the request fails and the update blocks.

Centreon 19.10.10 : 

```
CREATE TABLE `cb_list` (
	`cb_list_id` INT(11) NOT NULL,
	`cb_field_id` INT(11) NOT NULL,
	`default_value` VARCHAR(255) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	PRIMARY KEY (`cb_list_id`, `cb_field_id`) USING BTREE,
	UNIQUE INDEX `cb_field_idx_01` (`cb_field_id`) USING BTREE,
	INDEX `fk_cb_list_1` (`cb_field_id`) USING BTREE,
	CONSTRAINT `fk_cb_list_1` FOREIGN KEY (`cb_field_id`) REFERENCES `centreon`.`cb_field` (`cb_field_id`) ON UPDATE NO ACTION ON DELETE CASCADE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
```

**Comment by lpinsivy** [comment]
We didn't manage 2.8.x version anymore.

**Pull request closed without merging**
