### PR TITLE
(fix) MySQL strict mode issues

### PR DESCRIPTION
**Pull request by lgcosta**
<h1> Pull Request Template </h1>

<h2> Description </h2>

SQL code changes needed to maintain compatibility with MySQL/MariaDB/Percona strict mode

With cooperation of this PR #7529 (thanks @leblanc-simon)

<h2> Type of change </h2>

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [x] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

<h2> Target serie </h2>

- [ ] 2.8.x
- [ ] 18.10.x
- [x] 19.04.x (master)

<h2> How this pull request can be tested ? </h2>

Using a version of Mariadb above 10.3.x or enable the strict mode in the server, more information:

- https://mariadb.com/kb/en/library/sql-mode/
- https://mariadb.com/kb/en/library/server-system-variables/#sql_mode

<h2> Checklist </h2>

<h5> Community contributors & Centreon team </h5>

- [ ] I followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

<h5> Centreon team only </h5>

- [ ] I have made sure that the **unit tests** related to the story are successful.
- [ ] I have made sure that **unit tests covers 80%** of the code written for the story.
- [ ] I have made sure that **acceptance tests** related to the story are successful (**local and CI**)

### CODE REVIEW

**Comment by sc979** [comment]
@lgcosta ,
Please, could you replace the : 
- intval($XXX) with (int)$XXX
- fetchRow() with fetch()
- DBRESULT with dbResult
Thanks
sc979

**Comment by lgcosta** [comment]
> @lgcosta ,
> Please, could you replace the :
> 
> * intval($XXX) with (int)$XXX
> * fetchRow() with fetch()
> * DBRESULT with dbResult
>   Thanks
>   sc979

I will review and align all of these `dbfunction.php` with this formatting and any other codestyle that has to change.

Thanks

**Comment by leblanc-simon** [comment]
Hi @ganoze , there is any chance to view this PR merged into 18.10 branch ?

**Comment by ganoze** [comment]
@leblanc-simon Unfortunately no. The 18.10 release serie is not compatible with MariaDB strict mode and we only release bugfixes for released versions. So this PR and the MariaDB strict mode compatibility will make it in the 19.10 serie that will be released in October.

**Comment by leblanc-simon** [comment]
OK, thanks for all

**Comment by lpinsivy** [comment]
Replace : #6809

**Pull request merged**
