### PR TITLE
fix problem with curbe template: cannot change any parameters on cuvre template due to a problem with validator

### PR DESCRIPTION
**Pull request by julienmathis**
## Description

cannot change any parameters on cuvre template due to a problem with validator
By default 2 rules were used to check if they are another entry with the same name. It's ok for new entry but for update case, it's not possible because the system will always find the entry that we are currently updating.

Seems to correspond to this pb: MON-24923

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.04.x
- [ ] 22.10.x
- [x] 23.04.x
- [x] 23.10.x
- [x] 24.04.x (master)

<h2> How this pull request can be tested ? </h2>

just edit a curve and check that you can validate the form. 
Before no. After yes.

### CODE REVIEW

**Review by wtermellil — DISMISSED** [review]

**Comment by cgagnaire** [comment]
😭  https://github.com/centreon/centreon/pull/2957
Let's see which one is merged, the boss' one or the one from a simple community user!
Mine is only 2 months old so...

**Comment by julienmathis** [comment]
> 😭 #2957 Let's see which one is merged, the boss' one or the one from a simple community user! Mine is only 2 months old so...

As I can see, the fix is not on the same problem! No ?

**Comment by cgagnaire** [comment]
It's on the same problem, we just didn't fix it the same way. And I added another fix when a host/service couple is selected in the curve template (which was actually not saved).

**Comment by a-launois** [comment]
Seems to correspond to this pb: https://centreon.atlassian.net/browse/MON-24923

**Comment by a-launois** [comment]
This has been fixed in this PR: https://github.com/centreon/centreon/pull/4651

**Pull request closed without merging**
