### PR TITLE
New Feature Keycloak SSO auth

### PR DESCRIPTION
**Pull request by wallforfry**
**Keycloak SSO Login**

This feature add to Centreon Web the ability for user to login in Centreon with [Keycloak SSO](https://www.keycloak.org/about.html) provider.

- There are just some additions in centreonAuth.SSO.class.php file to allow Centreon call Keycloak API.
- A new section is added in 'Administration/Parameters' to provide all informations needed for Keycloak API.
- The documentation is up to date in HowTo section just after old SSO login chapter.

### CODE REVIEW

**Comment by lpinsivy** [comment]
@wallforfry thank you very much for this very good pull request including help and documentation!

In order to test your developments, can you provide us with a keycloak configuration (if possible a demo docker) and that of Centreon?

**Comment by lpinsivy** [comment]
@wallforfry thank you for the testing method. It's working very well.

We will integrate this on next major version.

Can you make a little change: don't display "login", "password" & "connect" button if (Keycloak is enabled && "SSO only" is checked)?

**Comment by wallforfry** [comment]
I think that is a bad behavior because administrator may need a fallback login system.
Can I add the same behavior as SSO with new fields (Keycloak Mode, Keycloak trusted client adresses, Keycloak blacklist client adresseses) ? And if "Keycloak Only" mode is selected display only login button and not any username/password fields

**Comment by lpinsivy** [comment]
@wallforfry thank for your changes.

It is possible to make a docker with this configuration of "Centreon client" to add this in our acceptance tests during build process?

**Comment by wallforfry** [comment]
@lpinsivy I'll create a Dockerfile of Keycloak with _Centreon_ configuration and user _admin_.
I need few more informations : 
 - What is the centreon dns name or IP ?
With this Dockerfile, you will need to fill centreon parameters with the secret that I'll provide to you.

**Comment by wallforfry** [comment]
@lpinsivy So, I succeed to create Keycloak Dockerfile with wildcard IP : no need of centreon domain-name/IP.
- Just run `$ docker run -dt --network host --name keycloak wallforfry/keycloak-centreon` 
- Compleate Centreon params with : 
  - Keycloak Server Url : http://YOUR_KEYCLOAK_HOST_IP:8080/auth
  - Keycloak Redirect Url : http://YOUR_CENTREON_IP/centreon/index.php
  - Keycloak Client Realm : master
  - Keycloak Client ID : Centreon
  - Keycloak Client Secret : _3c1ffe8b-5c2c-4c93-8d87-21a9ea28bfff_
- After that, you will be able to login in Centreon with admin/admin Keycloak account for your tests

**Comment by lpinsivy** [comment]
@wallforfry thank you I will test it

**Comment by wallforfry** [comment]
Hi @lpinsivy ! what about your tests ?

**Comment by lpinsivy** [comment]
New PR #7700 made for 19.10.0 with rebased

**Pull request closed without merging**
