### PR TITLE
2.8.24 release secfixes

### PR DESCRIPTION
**Pull request by uncleflo**
See pull requests [6141](https://github.com/centreon/centreon/pull/6141), [6049](https://github.com/centreon/centreon/pull/6049).

Jan 2018, Security fixes following an internal static scan done using HP Fortify, resolving 400 issues, minus 2.

These issues have been resolved and then tested if any improvement was not working.

Summary:

- Most changes involve adding escaping variables properly
- A file centreonEscaping.php was added, to ease escaping for future developers
- Changes are based on the idea that a malicious user could get administrative access

Please add this prospective branch to the latest live branch for the next release.

### CODE REVIEW

**Comment by adr-mo** [comment]
Hello @uncleflo thanks for the contribution appreciate it

Could you please rebase your PR branches on the latest 2.8.x branch please ?

Thanks

**Comment by uncleflo** [comment]
Which is 'the latest 2.8.x branch' ? Are you refering to the branch named '2.8.x', or to the branch named '2.8.24-release', which seems to be be the latest 2.8.x branch?

**Comment by adr-mo** [comment]
Hello @uncleflo it must be the 2.8.x branch.

2.8.24-release branch is a branch we use for our QA validation phase. It is destroyed afterwards and replaced by a tag on the 2.8.x branch.

Thanks

**Comment by uncleflo** [comment]
See https://github.com/centreon/centreon/pull/6406

**Pull request closed without merging**
